(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},p=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==
typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),r=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}};
r("Symbol",function(a){if(a)return a;var b=function(f,h){this.Fa=f;q(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.Fa};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
r("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!t(k,f)){var l=new b;q(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(I){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.l=(h+=Math.random()+1).toString();if(k){k=p(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!t(k,f))throw Error("WeakMap key fail: "+k);k[f][this.l]=l;return this};g.prototype.get=function(k){return c(k)&&t(k,f)?k[f][this.l]:void 0};g.prototype.has=function(k){return c(k)&&t(k,f)&&t(k[f],this.l)};
g.prototype.delete=function(k){return c(k)&&t(k,f)&&t(k[f],this.l)?delete k[f][this.l]:!1};return g});
r("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(p([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(I){return!1}}())return a;var b=new WeakMap,c=function(g){this.N={};this.j=f();
this.size=0;if(g){g=p(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.N[l.id]=[]);l.h?l.h.value=k:(l.h={next:this.j,u:this.j.u,head:this.j,key:g,value:k},l.list.push(l.h),this.j.u.next=l.h,this.j.u=l.h,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.h&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.N[g.id],g.h.u.next=g.h.next,g.h.next.u=g.h.u,g.h.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.N={};this.j=this.j.u=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).h};c.prototype.get=function(g){return(g=d(this,g).h)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,
g.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++h,b.set(k,l)):l="p_"+k;var n=g.N[l];if(n&&t(g.N,l))for(g=0;g<n.length;g++){var I=n[g];if(k!==k&&I.key!==I.key||k===I.key)return{id:l,list:n,index:g,h:I}}return{id:l,list:n,index:-1,h:void 0}},e=function(g,k){var l=g.j;return da(function(){if(l){for(;l.head!=g.j;)l=l.u;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.u=g.next=g.head=g},h=0;return c});
var u=this||self,ea=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},fa=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ha=function(a,b,c){return a.call.apply(a.bind,arguments)},ia=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,
d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return w.apply(null,arguments)},x=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.hb=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}},ja=function(a){return a};var y=function(a,b){this.width=a;this.height=b};m=y.prototype;m.clone=function(){return new y(this.width,this.height)};m.toString=function(){return"("+this.width+" x "+this.height+")"};m.aspectRatio=function(){return this.width/this.height};m.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};m.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
m.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};m.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};function ka(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function la(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var ma="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function na(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ma.length;f++)c=ma[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var pa=function(){var a=oa.play_url;this.I=oa.format_id;this.ab=a};pa.prototype.getSize=function(){return qa.get(this.I)};var ra={eb:7,fb:18,cb:22,gb:37},sa=[7,18,22,37],qa=new Map([[7,new y(320,240)],[18,new y(640,360)],[22,new y(1280,720)],[37,new y(1920,1080)]]);function z(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}x(z,Error);z.prototype.name="CustomError";var ta;function A(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])}x(A,z);A.prototype.name="AssertionError";function ua(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new A(""+e,f||[]);}
var B=function(a,b,c){a||ua("",null,b,Array.prototype.slice.call(arguments,2))},va=function(a,b){throw new A("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},C=function(a,b,c){"function"!==typeof a&&ua("Expected function but got %s: %s.",[ea(a),a],b,Array.prototype.slice.call(arguments,2))};var wa=Array.prototype.indexOf?function(a,b){B(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xa=Array.prototype.forEach?function(a,b){B(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},ya=Array.prototype.filter?
function(a,b){B(null!=a.length);return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var g=f[h];b.call(void 0,g,h,a)&&(d[e++]=g)}return d},za=Array.prototype.some?function(a,b){B(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};
function Aa(a,b){b=wa(a,b);var c;if(c=0<=b)B(null!=a.length),Array.prototype.splice.call(a,b,1);return c}function Ba(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ca(a,b){a.sort(b||Da)}function Da(a,b){return a>b?1:a<b?-1:0};var Ea=Object.freeze||function(a){return a};var Fa=function(){};var D=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.S=!1};D.prototype.stopPropagation=function(){this.S=!0};D.prototype.preventDefault=function(){this.defaultPrevented=!0};var Ga=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",function(){},b),u.removeEventListener("test",function(){},b)}catch(c){}return a}();function Ha(){var a=u.navigator;return a&&(a=a.userAgent)?a:""}function E(a){return-1!=Ha().indexOf(a)};var Ia=function(a){Ia[" "](a);return a};Ia[" "]=function(){};var Ja=E("Trident")||E("MSIE"),Ka=E("Gecko")&&!(-1!=Ha().toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),La=-1!=Ha().toLowerCase().indexOf("webkit")&&!E("Edge");var F=function(a,b){D.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.P=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=
b;if(b=a.relatedTarget){if(Ka){a:{try{Ia(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=La||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=La||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,
this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Ma[a.pointerType]||"";this.state=a.state;this.P=a;a.defaultPrevented&&F.L.preventDefault.call(this)}};
x(F,D);var Ma=Ea({2:"touch",3:"pen",4:"mouse"});F.prototype.stopPropagation=function(){F.L.stopPropagation.call(this);this.P.stopPropagation?this.P.stopPropagation():this.P.cancelBubble=!0};F.prototype.preventDefault=function(){F.L.preventDefault.call(this);var a=this.P;a.preventDefault?a.preventDefault():a.returnValue=!1};var G="closure_listenable_"+(1E6*Math.random()|0);var Na=0;var Oa=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Z=e;this.key=++Na;this.T=this.W=!1},H=function(a){a.T=!0;a.listener=null;a.proxy=null;a.src=null;a.Z=null};var J=function(a){this.src=a;this.i={};this.U=0};J.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.i[f];a||(a=this.i[f]=[],this.U++);var h=Pa(a,b,d,e);-1<h?(b=a[h],c||(b.W=!1)):(b=new Oa(b,this.src,f,!!d,e),b.W=c,a.push(b));return b};J.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.i))return!1;var e=this.i[a];b=Pa(e,b,c,d);return-1<b?(H(e[b]),B(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.i[a],this.U--),!0):!1};
var Qa=function(a,b){var c=b.type;c in a.i&&Aa(a.i[c],b)&&(H(b),0==a.i[c].length&&(delete a.i[c],a.U--))},Ra=function(a){var b=0,c;for(c in a.i){for(var d=a.i[c],e=0;e<d.length;e++)++b,H(d[e]);delete a.i[c];a.U--}};J.prototype.la=function(a,b,c,d){a=this.i[a.toString()];var e=-1;a&&(e=Pa(a,b,c,d));return-1<e?a[e]:null};
J.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return la(this.i,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};var Pa=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.T&&f.listener==b&&f.capture==!!c&&f.Z==d)return e}return-1};var Sa="closure_lm_"+(1E6*Math.random()|0),Ta={},Ua=0,Wa=function(a,b,c,d,e){if(d&&d.once)Va(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Wa(a,b[f],c,d,e);else c=Xa(c),a&&a[G]?(d=v(d)?!!d.capture:!!d,Ya(a),a.s.add(String(b),c,!1,d,e)):Za(a,b,c,!1,d,e)},Za=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,g=$a(a);g||(a[Sa]=g=new J(a));c=g.add(b,c,d,h,f);if(!c.proxy){d=ab();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Ga||(e=h),void 0===
e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(bb(b.toString()),d);else if(a.addListener&&a.removeListener)B("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ua++}},ab=function(){var a=cb,b=function(c){return a.call(b.src,b.listener,c)};return b},Va=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Va(a,b[f],c,d,e);else c=Xa(c),a&&a[G]?a.s.add(String(b),
c,!0,v(d)?!!d.capture:!!d,e):Za(a,b,c,!0,d,e)},db=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)db(a,b[f],c,d,e);else d=v(d)?!!d.capture:!!d,c=Xa(c),a&&a[G]?a.s.remove(String(b),c,d,e):a&&(a=$a(a))&&(b=a.la(b,c,d,e))&&eb(b)},eb=function(a){if("number"!==typeof a&&a&&!a.T){var b=a.src;if(b&&b[G])Qa(b.s,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(bb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);
Ua--;(c=$a(b))?(Qa(c,a),0==c.U&&(c.src=null,b[Sa]=null)):H(a)}}},bb=function(a){return a in Ta?Ta[a]:Ta[a]="on"+a},cb=function(a,b){if(a.T)a=!0;else{b=new F(b,this);var c=a.listener,d=a.Z||a.src;a.W&&eb(a);a=c.call(d,b)}return a},$a=function(a){a=a[Sa];return a instanceof J?a:null},fb="__closure_events_fn_"+(1E9*Math.random()>>>0),Xa=function(a){B(a,"Listener can not be null.");if("function"===typeof a)return a;B(a.handleEvent,"An object listener must have handleEvent method.");a[fb]||(a[fb]=function(b){return a.handleEvent(b)});
return a[fb]};var gb=function(){};var hb;var K=function(a,b){this.ra=a===ib&&b||"";this.Ga=jb};K.prototype.Ba=!0;K.prototype.za=function(){return this.ra};K.prototype.toString=function(){return"Const{"+this.ra+"}"};var jb={},ib={};var L=function(a,b){this.oa=b===kb?a:""};L.prototype.toString=function(){return this.oa+""};L.prototype.Ba=!0;L.prototype.za=function(){return this.oa.toString()};var lb=function(a){if(a instanceof L&&a.constructor===L)return a.oa;va("expected object of type TrustedResourceUrl, got '"+a+"' of type "+ea(a));return"type_error:TrustedResourceUrl"},kb={};var nb=function(a,b){a:{try{var c=a&&a.ownerDocument,d=c&&(c.defaultView||c.parentWindow);d=d||u;if(d.Element&&d.Location){var e=d;break a}}catch(h){}e=null}if(e&&"undefined"!=typeof e.HTMLScriptElement&&(!a||!(a instanceof e.HTMLScriptElement)&&(a instanceof e.Location||a instanceof e.Element))){if(v(a))try{var f=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(h){f="<object could not be stringified>"}else f=void 0===a?"undefined":null===a?"null":typeof a;va("Argument is not a %s (or a non-Element, non-Location mock); got: %s",
"HTMLScriptElement",f)}a:{e=(a.ownerDocument&&a.ownerDocument.defaultView||u).document;if(e.querySelector&&(e=e.querySelector("script[nonce]"))&&(e=e.nonce||e.getAttribute("nonce"))&&mb.test(e))break a;e=""}e&&a.setAttribute("nonce",e);a.src=lb(b)},mb=/^[\w+/_-]+[=]{0,2}$/;var ob=function(){return"background-image".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})},qb=function(){return pb.replace(RegExp("(^|[\\s]+)([a-z])","g"),function(a,b,c){return b+c.toUpperCase()})};var sb=function(a,b){ka(b,function(c,d){c&&"object"==typeof c&&c.Ba&&(c=c.za());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:rb.hasOwnProperty(d)?a.setAttribute(rb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},rb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",
width:"width"},tb=function(a,b,c,d){function e(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(;d<c.length;d++){var f=c[d];if(!fa(f)||v(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(v(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){h="function"==typeof f.item;break a}}h=!1}xa(h?Ba(f):f,e)}}},ub=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},vb=function(a){return a&&
a.parentNode?a.parentNode.removeChild(a):null},wb=function(a){this.O=a||u.document||document};m=wb.prototype;m.ya=function(){};m.getElementsByTagName=function(a,b){return(b||this.O).getElementsByTagName(String(a))};m.X=function(a,b,c){var d=this.O,e=arguments,f=e[1],h=ub(d,String(e[0]));f&&("string"===typeof f?h.className=f:Array.isArray(f)?h.className=f.join(" "):sb(h,f));2<e.length&&tb(d,h,e,2)};m.createElement=function(a){return ub(this.O,a)};m.createTextNode=function(a){return this.O.createTextNode(String(a))};
m.appendChild=function(a,b){B(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};m.append=function(a,b){var c=a;B(c,"Node cannot be null or undefined.");tb(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments,1)};m.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
m.removeNode=vb;m.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var M=function(){this.s=new J(this);this.Ha=this;this.na=null};x(M,Fa);M.prototype[G]=!0;M.prototype.pa=function(a){this.na=a};M.prototype.addEventListener=function(a,b,c,d){Wa(this,a,b,c,d)};M.prototype.removeEventListener=function(a,b,c,d){db(this,a,b,c,d)};
M.prototype.dispatchEvent=function(a){Ya(this);var b=this.na;if(b){var c=[];for(var d=1;b;b=b.na)c.push(b),B(1E3>++d,"infinite loop")}b=this.Ha;d=a.type||a;if("string"===typeof a)a=new D(a,b);else if(a instanceof D)a.target=a.target||b;else{var e=a;a=new D(d,b);na(a,e)}e=!0;if(c)for(var f=c.length-1;!a.S&&0<=f;f--){var h=a.currentTarget=c[f];e=N(h,d,!0,a)&&e}a.S||(h=a.currentTarget=b,e=N(h,d,!0,a)&&e,a.S||(e=N(h,d,!1,a)&&e));if(c)for(f=0;!a.S&&f<c.length;f++)h=a.currentTarget=c[f],e=N(h,d,!1,a)&&
e;return e};var N=function(a,b,c,d){b=a.s.i[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.T&&h.capture==c){var g=h.listener,k=h.Z||h.src;h.W&&Qa(a.s,h);e=!1!==g.call(k,d)&&e}}return e&&!d.defaultPrevented};M.prototype.la=function(a,b,c,d){return this.s.la(String(a),b,c,d)};M.prototype.hasListener=function(a,b){return this.s.hasListener(void 0!==a?String(a):void 0,b)};var Ya=function(a){B(a.s,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var xb={};var O=function(){};O.ma=void 0;O.Na=function(){return O.ma?O.ma:O.ma=new O};O.prototype.Sa=0;O.prototype.Qa="";var P=function(a){M.call(this);a||(a=ta||(ta=new wb));this.wa=a;this.l=null;this.J=!1;this.C=null;this.Aa=void 0;this.ha=this.ia=this.g=null};x(P,M);m=P.prototype;m.Pa=O.Na();m.getId=function(){var a;(a=this.l)||(a=this.Pa,a=this.l=a.Qa+":"+(a.Sa++).toString(36));return a};m.ya=function(){return this.C};m.getParent=function(){return this.g};m.pa=function(a){if(this.g&&this.g!=a)throw Error("Method not supported");P.L.pa.call(this,a)};m.X=function(){this.C=this.wa.createElement("DIV")};
var zb=function(a){a.J=!0;yb(a,function(b){!b.J&&b.ya()&&zb(b)})},Ab=function(a){yb(a,function(b){b.J&&Ab(b)});a.Aa&&Ra(a.Aa);a.J=!1},yb=function(a,b){a.ia&&a.ia.forEach(b,void 0)};
P.prototype.removeChild=function(a,b){if(a){var c="string"===typeof a?a:a.getId();this.ha&&c?(a=this.ha,a=(null!==a&&c in a?a[c]:void 0)||null):a=null;if(c&&a){var d=this.ha;c in d&&delete d[c];Aa(this.ia,a);b&&(Ab(a),a.C&&vb(a.C));b=a;if(null==b)throw Error("Unable to set parent component");b.g=null;P.L.pa.call(b,null)}}if(!a)throw Error("Child is not in parent component");return a};var Bb=function(a){P.call(this,a)};x(Bb,P);Bb.prototype.xa=function(){return null};function Cb(){};var Q=function(a,b){this.Ra=100;this.Ka=a;this.Va=b;this.ba=0;this.j=null};Q.prototype.get=function(){if(0<this.ba){this.ba--;var a=this.j;this.j=a.next;a.next=null}else a=this.Ka();return a};Q.prototype.put=function(a){this.Va(a);this.ba<this.Ra&&(this.ba++,a.next=this.j,this.j=a)};var Db,Eb=function(){var a=u.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!E("Presto")&&(a=function(){var e=ub(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var h="callImmediate"+Math.random(),g="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=w(function(k){if(("*"==g||k.origin==g)&&k.data==h)this.port1.onmessage()},
this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(h,g)}}});if("undefined"!==typeof a&&!E("Trident")&&!E("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.ta;c.ta=null;e()}};return function(e){d.next={ta:e};d=d.next;b.port2.postMessage(0)}}return function(e){u.setTimeout(e,0)}};function Fb(a){u.setTimeout(function(){throw a;},0)};var Gb=function(){this.ea=this.F=null};Gb.prototype.add=function(a,b){var c=Hb.get();c.set(a,b);this.ea?this.ea.next=c:(B(!this.F),this.F=c);this.ea=c};Gb.prototype.remove=function(){var a=null;this.F&&(a=this.F,this.F=this.F.next,this.F||(this.ea=null),a.next=null);return a};var Hb=new Q(function(){return new Ib},function(a){return a.reset()}),Ib=function(){this.next=this.scope=this.ka=null};Ib.prototype.set=function(a,b){this.ka=a;this.scope=b;this.next=null};
Ib.prototype.reset=function(){this.next=this.scope=this.ka=null};var Jb,Kb=!1,Lb=new Gb,Nb=function(a,b){Jb||Mb();Kb||(Jb(),Kb=!0);Lb.add(a,b)},Mb=function(){if(u.Promise&&u.Promise.resolve){var a=u.Promise.resolve(void 0);Jb=function(){a.then(Ob)}}else Jb=function(){var b=Ob;"function"!==typeof u.setImmediate||u.Window&&u.Window.prototype&&!E("Edge")&&u.Window.prototype.setImmediate==u.setImmediate?(Db||(Db=Eb()),Db(b)):u.setImmediate(b)}},Ob=function(){for(var a;a=Lb.remove();){try{a.ka.call(a.scope)}catch(b){Fb(b)}Hb.put(a)}Kb=!1};var Pb=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var T=function(a){this.m=0;this.v=void 0;this.G=this.o=this.g=null;this.Y=this.ja=!1;if(a!=gb)try{var b=this;a.call(void 0,function(c){R(b,2,c)},function(c){if(!(c instanceof S))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}R(b,3,c)})}catch(c){R(this,3,c)}},Qb=function(){this.next=this.context=this.K=this.D=this.B=null;this.V=!1};Qb.prototype.reset=function(){this.context=this.K=this.D=this.B=null;this.V=!1};
var Rb=new Q(function(){return new Qb},function(a){a.reset()}),Sb=function(a,b,c){var d=Rb.get();d.D=a;d.K=b;d.context=c;return d};T.prototype.then=function(a,b,c){null!=a&&C(a,"opt_onFulfilled should be a function.");null!=b&&C(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Tb(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};T.prototype.$goog_Thenable=!0;T.prototype.Wa=function(a,b){return Tb(this,null,a,b)};
T.prototype.catch=T.prototype.Wa;T.prototype.cancel=function(a){if(0==this.m){var b=new S(a);Nb(function(){Ub(this,b)},this)}};
var Ub=function(a,b){if(0==a.m)if(a.g){var c=a.g;if(c.o){for(var d=0,e=null,f=null,h=c.o;h&&(h.V||(d++,h.B==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.m&&1==d?Ub(c,b):(f?(d=f,B(c.o),B(null!=d),d.next==c.G&&(c.G=d),d.next=d.next.next):Vb(c),Wb(c,e,3,b)))}a.g=null}else R(a,3,b)},Yb=function(a,b){a.o||2!=a.m&&3!=a.m||Xb(a);B(null!=b.D);a.G?a.G.next=b:a.o=b;a.G=b},Tb=function(a,b,c,d){var e=Sb(null,null,null);e.B=new T(function(f,h){e.D=b?function(g){try{var k=b.call(d,g);f(k)}catch(l){h(l)}}:f;
e.K=c?function(g){try{var k=c.call(d,g);void 0===k&&g instanceof S?h(g):f(k)}catch(l){h(l)}}:h});e.B.g=a;Yb(a,e);return e.B};T.prototype.Ya=function(a){B(1==this.m);this.m=0;R(this,2,a)};T.prototype.Za=function(a){B(1==this.m);this.m=0;R(this,3,a)};
var R=function(a,b,c){if(0==a.m){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.m=1;a:{var d=c,e=a.Ya,f=a.Za;if(d instanceof T){null!=e&&C(e,"opt_onFulfilled should be a function.");null!=f&&C(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Yb(d,Sb(e||gb,f||null,a));var h=!0}else if(Pb(d))d.then(e,f,a),h=!0;else{if(v(d))try{var g=d.then;if("function"===typeof g){Zb(d,g,e,f,a);h=!0;break a}}catch(k){f.call(a,k);h=!0;
break a}h=!1}}h||(a.v=c,a.m=b,a.g=null,Xb(a),3!=b||c instanceof S||$b(a,c))}},Zb=function(a,b,c,d,e){var f=!1,h=function(k){f||(f=!0,c.call(e,k))},g=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,h,g)}catch(k){g(k)}},Xb=function(a){a.ja||(a.ja=!0,Nb(a.Ma,a))},Vb=function(a){var b=null;a.o&&(b=a.o,a.o=b.next,b.next=null);a.o||(a.G=null);null!=b&&B(null!=b.D);return b};T.prototype.Ma=function(){for(var a;a=Vb(this);)Wb(this,a,this.m,this.v);this.ja=!1};
var Wb=function(a,b,c,d){if(3==c&&b.K&&!b.V)for(;a&&a.Y;a=a.g)a.Y=!1;if(b.B)b.B.g=null,ac(b,c,d);else try{b.V?b.D.call(b.context):ac(b,c,d)}catch(e){bc.call(null,e)}Rb.put(b)},ac=function(a,b,c){2==b?a.D.call(a.context,c):a.K&&a.K.call(a.context,c)},$b=function(a,b){a.Y=!0;Nb(function(){a.Y&&bc.call(null,b)})},bc=Fb,S=function(a){z.call(this,a)};x(S,z);S.prototype.name="cancel";/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var U=function(a,b){this.ca=[];this.Ca=a;this.va=b||null;this.R=this.H=!1;this.v=void 0;this.qa=this.sa=this.fa=!1;this.da=0;this.g=null;this.ga=0};x(U,Cb);U.prototype.cancel=function(a){if(this.H)this.v instanceof U&&this.v.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.ga--,0>=b.ga&&b.cancel())}this.Ca?this.Ca.call(this.va,this):this.qa=!0;this.H||cc(this,new V(this))}};U.prototype.ua=function(a,b){this.fa=!1;dc(this,a,b)};
var dc=function(a,b,c){a.H=!0;a.v=c;a.R=!b;ec(a)},gc=function(a){if(a.H){if(!a.qa)throw new fc(a);a.qa=!1}},cc=function(a,b){gc(a);hc(b);dc(a,!1,b)},hc=function(a){B(!(a instanceof U),"An execution sequence may not be initiated with a blocking Deferred.")},jc=function(a,b){ic(a,b,null)},ic=function(a,b,c,d){B(!a.sa,"Blocking Deferreds can not be re-used");a.ca.push([b,c,d]);a.H&&ec(a)};
U.prototype.then=function(a,b,c){var d,e,f=new T(function(h,g){e=h;d=g});ic(this,e,function(h){h instanceof V?f.cancel():d(h);return kc},this);return f.then(a,b,c)};U.prototype.$goog_Thenable=!0;
var lc=function(a){return za(a.ca,function(b){return"function"===typeof b[1]})},kc={},ec=function(a){if(a.da&&a.H&&lc(a)){var b=a.da,c=W[b];c&&(u.clearTimeout(c.l),delete W[b]);a.da=0}a.g&&(a.g.ga--,delete a.g);b=a.v;for(var d=c=!1;a.ca.length&&!a.fa;){var e=a.ca.shift(),f=e[0],h=e[1];e=e[2];if(f=a.R?h:f)try{var g=f.call(e||a.va,b);g===kc&&(g=void 0);void 0!==g&&(a.R=a.R&&(g==b||g instanceof Error),a.v=b=g);if(Pb(b)||"function"===typeof u.Promise&&b instanceof u.Promise)d=!0,a.fa=!0}catch(k){b=k,
a.R=!0,lc(a)||(c=!0)}}a.v=b;d&&(g=w(a.ua,a,!0),d=w(a.ua,a,!1),b instanceof U?(ic(b,g,d),b.sa=!0):b.then(g,d));c&&(b=new mc(b),W[b.l]=b,a.da=b.l)},fc=function(){z.call(this)};x(fc,z);fc.prototype.message="Deferred has already fired";fc.prototype.name="AlreadyCalledError";var V=function(){z.call(this)};x(V,z);V.prototype.message="Deferred was canceled";V.prototype.name="CanceledError";var mc=function(a){this.l=u.setTimeout(w(this.Xa,this),0);this.La=a};
mc.prototype.Xa=function(){B(W[this.l],"Cannot throw an error that is not scheduled.");delete W[this.l];throw this.La;};var W={};var sc=function(){var a=nc,b={},c=b.document||document,d=lb(a).toString(),e=(new wb(c)).createElement("SCRIPT"),f={Da:e,Ea:void 0},h=new U(oc,f),g=null,k=null!=b.timeout?b.timeout:5E3;0<k&&(g=window.setTimeout(function(){pc(e,!0);cc(h,new qc(1,"Timeout reached for loading script "+d))},k),f.Ea=g);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(pc(e,b.ib||!1,g),gc(h),hc(null),dc(h,!0,null))};e.onerror=function(){pc(e,!0,g);cc(h,new qc(0,"Error while loading script "+
d))};f=b.attributes||{};na(f,{type:"text/javascript",charset:"UTF-8"});sb(e,f);nb(e,a);rc(c).appendChild(e);return h},rc=function(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement},oc=function(){if(this&&this.Da){var a=this.Da;a&&"SCRIPT"==a.tagName&&pc(a,!0,this.Ea)}},pc=function(a,b,c){null!=c&&u.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){vb(a)},0)},qc=function(a,
b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);z.call(this,c);this.code=a};x(qc,z);var uc=function(a,b,c,d){P.call(this,d);this.bb=a;this.M=tc(b);c=c||{};this.Ja=!!c.autoplay;this.Ia=!!c.allow_resize;this.aa=[]};x(uc,Bb);var vc;var X=new K(ib,"https://youtube.googleapis.com/iframe_api");X instanceof K&&X.constructor===K&&X.Ga===jb?vc=X.ra:(va("expected object of type Const, got '"+X+"'"),vc="type_error:Const");var wc=vc,xc;
if(void 0===hb){var yc=null,zc=u.trustedTypes;if(zc&&zc.createPolicy)try{yc=zc.createPolicy("goog#html",{createHTML:ja,createScript:ja,createScriptURL:ja})}catch(a){u.console&&u.console.error(a.message)}hb=yc}var Ac=(xc=hb)?xc.createScriptURL(wc):wc,nc=new L(Ac,kb),Bc=new y(320,240),Cc={7:"small",18:"medium",22:"hd720",37:"hd1080"},Dc=new y(480,360),tc=function(a){a=ya(a,function(b){a:{for(var c in ra)if(ra[c]==b.I){b=!0;break a}b=!1}return b});Ca(a,function(b,c){return wa(sa,b.I)-wa(sa,c.I)});return a};
m=uc.prototype;m.xa=function(){var a=Bc.clone();var b=this.jb;if(b&&(b.width>=a.width||b.height>=a.height))a=b.clone();else{var c;b=this.kb;for(var d=this.M.length,e=0;e<d;e++){var f=this.M[e].getSize(),h=f&&b&&(f.width>b.width||f.height>b.height);f&&(!c||f.width>c.width)&&!h&&(c=f)}c&&(c.width>=a.width||c.height>=a.height)&&(a=c.clone())}return new y(a.width,a.height+38)};m.X=function(){uc.L.X.call(this);jc(sc(),w(function(){YT.ready(w(this.Ta,this))},this))};
m.Ta=function(){var a=this.xa();this.A=new YT.Player(this.bb,{width:a.width,height:a.height,playerVars:{autohide:"1",enablecastapi:0,html5:"1",ps:"blogger"},events:{onStateChange:w(this.Oa,this),onReady:w(this.Ua,this)}});if(this.aa){a=p(this.aa);for(var b=a.next();!b.done;b=a.next())b=b.value,this.A.addEventListener(b.name,b.listener)}this.aa=[]};m.Oa=function(a){this.dispatchEvent(new Ec("b",a.data))};
m.Ua=function(){var a=this,b={fmt_list:Fc(this),url_encoded_fmt_stream_map:Gc(this),video_id:"picasacid"};this.Ia&&(this.A.setSizeStyle(!0,!1),this.A.addEventListener("SIZE_CLICKED",function(c){a.A.setSizeStyle(!0,c.data)}));this.Ja?this.A.loadVideoByPlayerVars(b):this.A.cueVideoByPlayerVars(b)};
var Fc=function(a){for(var b=[],c=0;c<a.M.length;++c){var d=b,e=d.push,f=a.M[c],h=f.getSize();h||(h=Dc);e.call(d,f.I+"/"+h.width+"x"+h.height)}return b.reverse().join(",")},Gc=function(a){for(var b=[],c=0;c<a.M.length;++c){var d=a.M[c],e=d.I;d="url="+encodeURIComponent(String(d.ab))+"&itag="+e+"&type="+encodeURIComponent("video/mp4;")+"&quality="+Cc[e];b.push(d)}return b.reverse().join(",")},Ec=function(a){D.call(this,a)};x(Ec,D);var Hc=u.document.getElementById("videocontainer");if(VIDEO_CONFIG.thumbnail){var Ic=document.querySelector(".thumbnail-holder"),Jc="url("+VIDEO_CONFIG.thumbnail+")",Kc,Y=xb["background-image"];if(!Y){var pb=ob();Y=pb;if(void 0===Ic.style[pb]){var Lc=(La?"Webkit":Ka?"Moz":Ja?"ms":null)+qb();void 0!==Ic.style[Lc]&&(Y=Lc)}xb["background-image"]=Y}(Kc=Y)&&(Ic.style[Kc]=Jc)}for(var Mc=[],Nc=p(VIDEO_CONFIG.streams),Oc=Nc.next();!Oc.done;Oc=Nc.next()){var oa=Oc.value;Mc.push(new pa)}
var Z=new uc(Hc,Mc,{autoplay:!0,allow_resize:VIDEO_CONFIG.allow_resize});if(VIDEO_CONFIG.allow_resize&&VIDEO_CONFIG.iframe_id){var Pc=function(a){window.parent.postMessage({name:"video_resize",iframe_id:VIDEO_CONFIG.iframe_id,widescreen:a.data},document.referrer)};Z.A?Z.A.addEventListener("SIZE_CLICKED",Pc):Z.aa.push({name:"SIZE_CLICKED",listener:Pc})}
Wa(Hc,"click",function(){if(Z.J)throw Error("Component already rendered");Z.C||Z.X();Hc?Hc.insertBefore(Z.C,null):Z.wa.O.body.appendChild(Z.C);Z.g&&!Z.g.J||zb(Z)});}).call(this);
